// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGkSlsTRLm7GZk-UCw05Obds3EohIoic',
    appId: '1:599743330966:android:b21f926fde3cde7a31a0b7',
    messagingSenderId: '599743330966',
    projectId: 'project0-93f4c',
    storageBucket: 'project0-93f4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEHjgcssFskHyQBTOXaR-wbvq4SqJVj10',
    appId: '1:599743330966:ios:1e49e2d49d9fce1631a0b7',
    messagingSenderId: '599743330966',
    projectId: 'project0-93f4c',
    storageBucket: 'project0-93f4c.appspot.com',
    iosBundleId: 'com.example.practice01App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEHjgcssFskHyQBTOXaR-wbvq4SqJVj10',
    appId: '1:599743330966:ios:1e49e2d49d9fce1631a0b7',
    messagingSenderId: '599743330966',
    projectId: 'project0-93f4c',
    storageBucket: 'project0-93f4c.appspot.com',
    iosBundleId: 'com.example.practice01App',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiTIV52KFBvaHPdb9K867wgQXFyGErq4w',
    appId: '1:599743330966:web:e84fd28ba76efc2a31a0b7',
    messagingSenderId: '599743330966',
    projectId: 'project0-93f4c',
    authDomain: 'project0-93f4c.firebaseapp.com',
    storageBucket: 'project0-93f4c.appspot.com',
    measurementId: 'G-836NC8B9LG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiTIV52KFBvaHPdb9K867wgQXFyGErq4w',
    appId: '1:599743330966:web:03fe1becb32ba51531a0b7',
    messagingSenderId: '599743330966',
    projectId: 'project0-93f4c',
    authDomain: 'project0-93f4c.firebaseapp.com',
    storageBucket: 'project0-93f4c.appspot.com',
    measurementId: 'G-LVCRK92QTW',
  );
}
